services:

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  config-server:
    build:
      context: .
      dockerfile: config-service/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
